name: demo-workflow

on: 
  push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4 
    - name: list file
      run: |
       echo "list files"
       ls -ltra
       cat README.md
       apt-get install neofetch -y
       neofetch > neofetch.txt
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: neofetch-artifact
        path: neofetch.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: test
      run: grep -i "ubuntu" neofetch.txt
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: neofetch-artifact

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: cat deploy
      run: cat neofetch.txt
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: neofetch-artifact